#!/bin/bash

 # Default policies
 sudo ufw default deny incoming
 sudo ufw default deny outgoing

 # Openvpn interface (adjust interface accordingly to your configuration)
 sudo ufw allow in on tun0
 sudo ufw allow out on tun0

 # Openvpn interface (adjust interface accordingly to your configuration)
 sudo ufw allow in on tap0
 sudo ufw allow out on tap0

 # Local Network (adjust ip accordingly to your configuration)
 sudo ufw allow in on wlan0 from 192.168.1.34/24
 sudo ufw allow out on wlan0 to 192.168.1.34/24

 # Openvpn (adjust port accordingly to your configuration)
 sudo ufw allow in on wlan0 from any port 1194
 sudo ufw allow out on wlan0 to any port 1194

 # DNS
 ufw allow in from any to any port 53
 ufw allow out from any to any port 53

  # DNS
 sudo ufw allow in from any to any port 443
 sudo ufw allow out from any to any port 443